### ISSUE TITLE
CI/CD pipeline?

### ISSUE THREAD

**Issue by ChrisJBurns** [mlewis7127/qldbguide#15]
Be interesting to know how this is deployed to AWS S3? Do you use AWS developer tools such as Amplify to deploy or is it a manual task of uploading the `public` directory to S3?

I could help with automation via Github actions if interested :) then again, if you're using Amplify then no pipeline is needed as Amplify is pretty handy for removing all work from the engineer.

**Comment by gregsimons** [comment]
@mlewis7127 has been doing the deployment and would be best to pick this up in terms of his preference. At the moment this is deployed via amplify

**Comment by ChrisJBurns** [comment]
In that case there's no need to implement a pipeline. Amplify is really good with building web applications as it pretty much does all of the work :) Happy for this to close

**Comment by gregsimons** [comment]
I think there might be some things that @mlewis7127 wanted to improve in the deployment process. @mlewis7127 - can we get some of these created as new tickets so potentially they could be picked up? Thanks for raising this!

**Comment by mlewis7127** [comment]
@ChrisJBurns as @gregsimons said, we've used Amplify which takes care of all the engineering work, and also supports the feature branch deploys. Thanks again for the offer to help. We're keen to get more people involved and would welcome the support
